name: mayavi-environment
channels:
  - conda-forge
dependencies:
  - python=2.7
  - numpy
  - matplotlib
  - ipython
  - ipywidgets
  - ipyevents
  - vtk=8.1.*
  - mayavi=4.6.*
  - jupyter=1.0.*
  - pip
  - pip:

    
